//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poD
    {
        public int id { get; set; }
        public int poId { get; set; }
        public string Itemno { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> disc { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
